server:
  port: 8080

spring:
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  main:
    banner-mode: off
  application:
    name: spring-actuator

  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  metrics:
    export:
      elastic:
        enabled: ${ELASTIC_ENABLED:false}
        step: 10s
        index: metrics
        host: http://elasticsearch:9200
        user-name: elastic
        password: changeme
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:false}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 100ms, 400ms, 500ms, 2000ms
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99

    tags:
      host: ${HOSTNAME:DOCKER}
      application: ${spring.application.name}

#  endpoint:
#    info:
#      enabled: true
#    prometheus:
#      enabled: true
#    auditevents:
#      enabled: true


  endpoints:
    jmx:
      exposure:
        exclude: "*"

    web:
      base-path: /actuator

      exposure:
        include: "*"
