version: "3.1"
services:
  spring-actuator:
    container_name: spring-actuator
    build:
      context: ../..
      dockerfile: configs/spring-actuator/Dockerfile
    ports:
      - '8080:8080'
    environment:
      ELASTIC_ENABLED: ${ELASTIC_ENABLED:-false}
      PROMETHEUS_ENABLED: ${PROMETHEUS_ENABLED:-false}
    networks:
      monitoring:
        aliases:
          - spring-actuator

networks:
  monitoring:
    external: true
