version: "3.1"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.6.1
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      monitoring:
        aliases:
          - prometheus

networks:
  monitoring:
    external: true
