version: "3.1"
services:
  grafana:
    container_name: grafana
    build: .
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"

    networks:
      monitoring:
        aliases:
          - grafana

networks:
  monitoring:
    external: true
